version: '3'
services:
  ambassador_backend:
    build: .
    image: yuchanhuang/ambassador:0.0.8
    environment:
      BOOTSTRAP_SERVICE: pkc-l7j7w.asia-east1.gcp.confluent.cloud:9092
      SECURITY_PROTOCOL: SASL_SSL
      SASL_USERNAME: EWGW6CHWHXQ6M2I3
      SASL_PASSWORD: lBYnFyIMYAjqtrOrdZA7THC0EYKafF2bc7kX5mjPMzy8+G7qy6KthRyOYXHidy91
      SASL_MECHANISMS: PLAIN
      GROUP_ID: myGroup
      DB_HOST: 35.221.227.158
      DB_DATABASE: ambassador
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: root
      KAFKA_TOPIC: ambassador_topic
      USERS_MS: http://usersms:8001
      REDIS_URL: redis://redis:6379/0
    command:
      - "/bin/bash"
      - "-c"
      - "python manage.py wait_for_db && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8003:8000"

  ambassador_queue:
    build: .
    image: yuchanhuang/ambassador:0.0.1
    environment:
      BOOTSTRAP_SERVICE: pkc-l7j7w.asia-east1.gcp.confluent.cloud:9092
      SECURITY_PROTOCOL: SASL_SSL
      SASL_USERNAME: EWGW6CHWHXQ6M2I3
      SASL_PASSWORD: lBYnFyIMYAjqtrOrdZA7THC0EYKafF2bc7kX5mjPMzy8+G7qy6KthRyOYXHidy91
      SASL_MECHANISMS: PLAIN
      GROUP_ID: myGroup
      DB_HOST: 35.221.227.158
      DB_DATABASE: ambassador
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: root
      KAFKA_TOPIC: ambassador_topic
      # USERS_MS: http://users-backend:8001
      USERS_MS: http://usersms:8001
    command:
      - "/bin/bash"
      - "-c"
      - "python manage.py wait_for_db && python consumer.py"

  redis:
    image: redis
    ports:
      - "6379:6379"
