apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: checkout-backend
  name: checkout-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: checkout-backend
  template:
    metadata:
      labels:
        io.kompose.service: checkout-backend
    spec:
      containers:
        - args:
            - sh
            - -c
            - python manage.py wait_for_db && python manage.py runserver 0.0.0.0:8000
          env:
            - name: BOOTSTRAP_SERVICE
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: BOOTSTRAP_SERVICE
            - name: CHECKOUT_URL
              value: # http://localhost:5000 frontend url
            - name: DB_DATABASE
              value: # database
            - name: DB_HOST
              value: # sql private ip
            - name: DB_PASSWORD
              value: # password
            - name: DB_PORT
              value: # port
            - name: DB_USERNAME
              value: # username
            - name: GROUP_ID
              value: # group id
            - name: KAFKA_TOPIC
              value: checkout_topic
            - name: SASL_MECHANISMS
              value: PLAIN
            - name: SASL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: SASL_PASSWORD
            - name: SASL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: SASL_USERNAME
            - name: SECURITY_PROTOCOL
              value: SASL_SSL
            - name: STRIPE_KEY
              value: sk_test_51JzApBJGUoxxhmAhUSA8mEFbAGN641J1kLKPSjMZhrnVXhv1SPe14n8eqUQBSxjHIYHyyz30a5VwqAHkmVhPzV4X00VjKKTkCn
            - name: USERS_MS
              value: http://users-backend:8001
          image: gcr.io/platinum-snow-289105/checkout:latest
          name: checkout-backend
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: checkout-queue
  name: checkout-queue
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: checkout-queue
  template:
    metadata:
      labels:
        io.kompose.service: checkout-queue
    spec:
      containers:
        - args:
            - /bin/bash
            - -c
            - python manage.py wait_for_db && python consumer.py
          env:
            - name: BOOTSTRAP_SERVICE
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: BOOTSTRAP_SERVICE
            - name: CHECKOUT_URL
              value: # http://localhost:5000 frontend
            - name: DB_DATABASE
              value: # database
            - name: DB_HOST
              value: # sql private
            - name: DB_PASSWORD
              value: # password
            - name: DB_PORT
              value: # port
            - name: DB_USERNAME
              value: # username
            - name: GROUP_ID
              value: # group id
            - name: KAFKA_TOPIC
              value: checkout_topic
            - name: SASL_MECHANISMS
              value: PLAIN
            - name: SASL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: SASL_PASSWORD
            - name: SASL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: SASL_USERNAME
            - name: SECURITY_PROTOCOL
              value: SASL_SSL
            - name: STRIPE_KEY
              value: sk_test_51JzApBJGUoxxhmAhUSA8mEFbAGN641J1kLKPSjMZhrnVXhv1SPe14n8eqUQBSxjHIYHyyz30a5VwqAHkmVhPzV4X00VjKKTkCn
            - name: USERS_MS
              value: http://users-backend:8001
          image: gcr.io/platinum-snow-289105/checkout:latest
          name: checkout-queue
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: checkout-backend
  name: checkout-backend
spec:
  ports:
    - name: "8004"
      port: 8004
      targetPort: 8000
  selector:
    io.kompose.service: checkout-backend